### ISSUE TITLE
Snackでの開発方法ドキュメントの作成

### ISSUE THREAD

**Issue by hane0817** [ritscc/Snack#33]

**Comment by 1uf3** [comment]
# SnackでのGit,Githubの使い方

## Gitの使い方

### 開発作業の流れ

1. mainブランチからdevブランチを作成
2. devブランチから実装する機能毎にfeatureブランチを作成
3. feature, docs, hotfixブランチでのPRはdevelopブランチにスカッシュマージ
4. リリース時点でdev → mainマージ

### 登場するブランチ

- main
　リリースした時点のソースコードを管理するブランチ
- dev (mainから派生)
　開発作業の主軸となるブランチ
- hotfix (mainから派生)
　公開中のもののバグ修正用ブランチ (hotfix-<Issue_number>-◯◯ 例: hotfix-1-xxなど)
- feature (devから派生)
　実装する機能毎のブランチ (feature-<Issue_number>-◯◯ 例: feature-1-xxなど)
- docs (devから派生)
　ドキュメントに対しての記述ブランチ (docs-<Issue_number>-◯◯ 例: docs-1-xxなど)
- fix (devから派生)
　開発中のもののバグ修正用ブランチ (fix-<Issue_number>-◯◯ 例: fix-1-xxなど)

## Githubの使い方

### 開発方法
SnackのProjectsから現在開発中のバージョンのプロジェクトを開き、Todoの中からやりたいIssueを選び、Asigneesに自分を追加する。

**Comment by 1uf3** [comment]
GitとGithubを分けるより開発手順のドキュメントに開発フローを書いておけばよさそう
